const foods = [
  { name: 'Arroz blanco cocido', category: 'cereales', caloriesPer100g: 130, defaultPortion: '1 taza (200g)' },
  { name: 'Arroz integral cocido', category: 'cereales', caloriesPer100g: 111, defaultPortion: '1 taza (200g)' },
  { name: 'Pasta cocida', category: 'cereales', caloriesPer100g: 131, defaultPortion: '1 taza (200g)' },
  { name: 'Pan blanco', category: 'cereales', caloriesPer100g: 265, defaultPortion: '1 rebanada (30g)' },
  { name: 'Pan integral', category: 'cereales', caloriesPer100g: 247, defaultPortion: '1 rebanada (30g)' },
  { name: 'Avena cocida', category: 'cereales', caloriesPer100g: 71, defaultPortion: '1 taza (240g)' },
  { name: 'Cereal de desayuno', category: 'cereales', caloriesPer100g: 378, defaultPortion: '1 taza (30g)' },
  { name: 'Tortilla de maíz', category: 'cereales', caloriesPer100g: 218, defaultPortion: '1 unidad (30g)' },
  { name: 'Quinoa cocida', category: 'cereales', caloriesPer100g: 120, defaultPortion: '1 taza (185g)' },
  { name: 'Papa cocida', category: 'tuberculos', caloriesPer100g: 87, defaultPortion: '1 unidad mediana (170g)' },
  { name: 'Papa frita', category: 'tuberculos', caloriesPer100g: 312, defaultPortion: '1 porción pequeña (100g)' },
  { name: 'Camote/batata cocido', category: 'tuberculos', caloriesPer100g: 86, defaultPortion: '1 unidad mediana (150g)' },
  { name: 'Yuca cocida', category: 'tuberculos', caloriesPer100g: 112, defaultPortion: '1 porción (150g)' },
  { name: 'Pollo a la plancha (pechuga)', category: 'carnes', caloriesPer100g: 165, defaultPortion: '1 pieza (150g)' },
  { name: 'Pollo frito', category: 'carnes', caloriesPer100g: 246, defaultPortion: '1 pieza (150g)' },
  { name: 'Carne de res magra cocida', category: 'carnes', caloriesPer100g: 250, defaultPortion: '1 porción (150g)' },
  { name: 'Carne molida cocida', category: 'carnes', caloriesPer100g: 260, defaultPortion: '1 taza (150g)' },
  { name: 'Cerdo asado', category: 'carnes', caloriesPer100g: 242, defaultPortion: '1 porción (150g)' },
  { name: 'Pescado blanco cocido', category: 'carnes', caloriesPer100g: 96, defaultPortion: '1 filete (150g)' },
  { name: 'Atún en agua', category: 'carnes', caloriesPer100g: 116, defaultPortion: '1 lata (140g)' },
  { name: 'Salmón cocido', category: 'carnes', caloriesPer100g: 208, defaultPortion: '1 filete (150g)' },
  { name: 'Huevo revuelto', category: 'huevos', caloriesPer100g: 149, defaultPortion: '2 huevos (100g)' },
  { name: 'Huevo cocido', category: 'huevos', caloriesPer100g: 155, defaultPortion: '1 unidad (50g)' },
  { name: 'Huevo frito', category: 'huevos', caloriesPer100g: 196, defaultPortion: '1 unidad (50g)' },
  { name: 'Leche entera', category: 'lacteos', caloriesPer100ml: 61, defaultPortion: '1 vaso (240ml)' },
  { name: 'Leche descremada', category: 'lacteos', caloriesPer100ml: 34, defaultPortion: '1 vaso (240ml)' },
  { name: 'Yogur natural', category: 'lacteos', caloriesPer100g: 61, defaultPortion: '1 pote (200g)' },
  { name: 'Queso blanco', category: 'lacteos', caloriesPer100g: 300, defaultPortion: '1 porción (40g)' },
  { name: 'Queso mozzarella', category: 'lacteos', caloriesPer100g: 280, defaultPortion: '1 porción (40g)' },
  { name: 'Queso cheddar', category: 'lacteos', caloriesPer100g: 403, defaultPortion: '1 rebanada (20g)' },
  { name: 'Mantequilla', category: 'lacteos', caloriesPer100g: 717, defaultPortion: '1 cucharada (14g)' },
  { name: 'Frijoles negros cocidos', category: 'legumbres', caloriesPer100g: 132, defaultPortion: '1 taza (200g)' },
  { name: 'Lentejas cocidas', category: 'legumbres', caloriesPer100g: 116, defaultPortion: '1 taza (200g)' },
  { name: 'Garbanzos cocidos', category: 'legumbres', caloriesPer100g: 139, defaultPortion: '1 taza (200g)' },
  { name: 'Arvejas cocidas', category: 'legumbres', caloriesPer100g: 84, defaultPortion: '1 taza (160g)' },
  { name: 'Habichuelas cocidas', category: 'legumbres', caloriesPer100g: 127, defaultPortion: '1 taza (200g)' },
  { name: 'Soya cocida', category: 'legumbres', caloriesPer100g: 141, defaultPortion: '1 taza (200g)' },
  { name: 'Brócoli cocido', category: 'verduras', caloriesPer100g: 35, defaultPortion: '1 taza (150g)' },
  { name: 'Espinaca cruda', category: 'verduras', caloriesPer100g: 23, defaultPortion: '1 taza (30g)' },
  { name: 'Zanahoria cruda', category: 'verduras', caloriesPer100g: 41, defaultPortion: '1 unidad (60g)' },
  { name: 'Lechuga', category: 'verduras', caloriesPer100g: 15, defaultPortion: '1 taza (50g)' },
  { name: 'Tomate', category: 'verduras', caloriesPer100g: 18, defaultPortion: '1 unidad mediana (120g)' },
  { name: 'Cebolla', category: 'verduras', caloriesPer100g: 40, defaultPortion: '1 unidad mediana (100g)' },
  { name: 'Pimiento', category: 'verduras', caloriesPer100g: 20, defaultPortion: '1 unidad (100g)' },
  { name: 'Pepino', category: 'verduras', caloriesPer100g: 15, defaultPortion: '1/2 unidad (100g)' },
  { name: 'Aguacate', category: 'verduras', caloriesPer100g: 160, defaultPortion: '1/2 unidad (100g)' },
  { name: 'Coliflor cocida', category: 'verduras', caloriesPer100g: 25, defaultPortion: '1 taza (100g)' },
  { name: 'Calabacín cocido', category: 'verduras', caloriesPer100g: 21, defaultPortion: '1 taza (180g)' },
  { name: 'Champiñones', category: 'verduras', caloriesPer100g: 22, defaultPortion: '1 taza (100g)' },
  { name: 'Maíz dulce', category: 'verduras', caloriesPer100g: 96, defaultPortion: '1 mazorca (100g)' },
  { name: 'Plátano maduro', category: 'frutas', caloriesPer100g: 89, defaultPortion: '1 unidad mediana (120g)' },
  { name: 'Plátano verde cocido', category: 'frutas', caloriesPer100g: 116, defaultPortion: '1 unidad mediana (150g)' },
  { name: 'Manzana', category: 'frutas', caloriesPer100g: 52, defaultPortion: '1 unidad mediana (180g)' },
  { name: 'Naranja', category: 'frutas', caloriesPer100g: 47, defaultPortion: '1 unidad mediana (150g)' },
  { name: 'Banana', category: 'frutas', caloriesPer100g: 89, defaultPortion: '1 unidad mediana (120g)' },
  { name: 'Uvas', category: 'frutas', caloriesPer100g: 69, defaultPortion: '1 taza (150g)' },
  { name: 'Fresas', category: 'frutas', caloriesPer100g: 32, defaultPortion: '1 taza (150g)' },
  { name: 'Mango', category: 'frutas', caloriesPer100g: 60, defaultPortion: '1 unidad (200g)' },
  { name: 'Papaya', category: 'frutas', caloriesPer100g: 43, defaultPortion: '1 taza (140g)' },
  { name: 'Piña', category: 'frutas', caloriesPer100g: 50, defaultPortion: '1 taza (150g)' },
  { name: 'Sandía', category: 'frutas', caloriesPer100g: 30, defaultPortion: '1 tajada (280g)' },
  { name: 'Melón', category: 'frutas', caloriesPer100g: 34, defaultPortion: '1 taza (150g)' },
  { name: 'Pera', category: 'frutas', caloriesPer100g: 57, defaultPortion: '1 unidad (180g)' },
  { name: 'Durazno', category: 'frutas', caloriesPer100g: 39, defaultPortion: '1 unidad (150g)' },
  { name: 'Mandarina', category: 'frutas', caloriesPer100g: 53, defaultPortion: '1 unidad (100g)' },
  { name: 'Limón', category: 'frutas', caloriesPer100g: 29, defaultPortion: '1 unidad (60g)' },
  { name: 'Coco rallado', category: 'frutas', caloriesPer100g: 354, defaultPortion: '1/4 taza (20g)' },
  { name: 'Almendras', category: 'frutos_secos', caloriesPer100g: 579, defaultPortion: '1 puñado (30g)' },
  { name: 'Nueces', category: 'frutos_secos', caloriesPer100g: 654, defaultPortion: '1 puñado (30g)' },
  { name: 'Maní', category: 'frutos_secos', caloriesPer100g: 567, defaultPortion: '1 puñado (30g)' },
  { name: 'Semillas de girasol', category: 'frutos_secos', caloriesPer100g: 584, defaultPortion: '1 puñado (30g)' },
  { name: 'Aceite de oliva', category: 'aceites', caloriesPer100ml: 884, defaultPortion: '1 cucharada (15ml)' },
  { name: 'Aceite vegetal', category: 'aceites', caloriesPer100ml: 884, defaultPortion: '1 cucharada (15ml)' },
  { name: 'Mayonesa', category: 'aceites', caloriesPer100g: 680, defaultPortion: '1 cucharada (15g)' },
  { name: 'Aderezo ranch', category: 'aceites', caloriesPer100g: 430, defaultPortion: '2 cucharadas (30g)' },
  { name: 'Azúcar blanca', category: 'endulzantes', caloriesPer100g: 387, defaultPortion: '1 cucharadita (4g)' },
  { name: 'Miel', category: 'endulzantes', caloriesPer100g: 304, defaultPortion: '1 cucharada (21g)' },
  { name: 'Mermelada', category: 'endulzantes', caloriesPer100g: 250, defaultPortion: '1 cucharada (20g)' },
  { name: 'Chocolate oscuro', category: 'dulces', caloriesPer100g: 546, defaultPortion: '1 barra pequeña (30g)' },
  { name: 'Chocolate con leche', category: 'dulces', caloriesPer100g: 535, defaultPortion: '1 barra pequeña (30g)' },
  { name: 'Galletas dulces', category: 'dulces', caloriesPer100g: 482, defaultPortion: '4 unidades (30g)' },
  { name: 'Pastel de chocolate', category: 'dulces', caloriesPer100g: 371, defaultPortion: '1 porción (80g)' },
  { name: 'Helado de vainilla', category: 'dulces', caloriesPer100g: 207, defaultPortion: '1 bola (80g)' },
  { name: 'Arroz con leche', category: 'dulces', caloriesPer100g: 127, defaultPortion: '1 taza (200g)' },
  { name: 'Flan', category: 'dulces', caloriesPer100g: 152, defaultPortion: '1 porción (100g)' },
  { name: 'Agua', category: 'bebidas', caloriesPer100ml: 0, defaultPortion: '1 vaso (240ml)' },
  { name: 'Café negro', category: 'bebidas', caloriesPer100ml: 1, defaultPortion: '1 taza (240ml)' },
  { name: 'Jugo de naranja', category: 'bebidas', caloriesPer100ml: 45, defaultPortion: '1 vaso (240ml)' },
  { name: 'Gaseosa cola', category: 'bebidas', caloriesPer100ml: 42, defaultPortion: '1 lata (355ml)' },
  { name: 'Cerveza', category: 'bebidas', caloriesPer100ml: 43, defaultPortion: '1 botella (355ml)' },
  { name: 'Vino tinto', category: 'bebidas', caloriesPer100ml: 85, defaultPortion: '1 copa (150ml)' },
  { name: 'Agua de coco', category: 'bebidas', caloriesPer100ml: 19, defaultPortion: '1 vaso (240ml)' },
  { name: 'Batido de proteína', category: 'bebidas', caloriesPer100ml: 42, defaultPortion: '1 vaso (300ml)' },
  { name: 'Sopa de verduras', category: 'sopas', caloriesPer100ml: 36, defaultPortion: '1 plato (250ml)' },
  { name: 'Sopa de pollo con fideos', category: 'sopas', caloriesPer100ml: 50, defaultPortion: '1 plato (250ml)' },
  { name: 'Sopa de frijoles', category: 'sopas', caloriesPer100ml: 60, defaultPortion: '1 plato (250ml)' },
  { name: 'Sopa de crema de verduras', category: 'sopas', caloriesPer100ml: 55, defaultPortion: '1 plato (250ml)' },
  { name: 'Arepa asada', category: 'cereales', caloriesPer100g: 219, defaultPortion: '1 unidad (100g)' },
  { name: 'Arepa frita', category: 'cereales', caloriesPer100g: 319, defaultPortion: '1 unidad (100g)' },
  { name: 'Cachapa', category: 'cereales', caloriesPer100g: 210, defaultPortion: '1 unidad (150g)' },
  { name: 'Empanada de pollo frita', category: 'cereales', caloriesPer100g: 280, defaultPortion: '1 unidad (100g)' },
  { name: 'Tequeños', category: 'cereales', caloriesPer100g: 380, defaultPortion: '3 unidades (60g)' },
  { name: 'Pabellón criollo', category: 'comidas', caloriesPer100g: 145, defaultPortion: '1 plato (400g)' },
  { name: 'Hallaca', category: 'comidas', caloriesPer100g: 250, defaultPortion: '1 unidad (200g)' },
  { name: 'Carne desmechada', category: 'carnes', caloriesPer100g: 195, defaultPortion: '1 porción (100g)' },
  { name: 'Churrasco', category: 'carnes', caloriesPer100g: 215, defaultPortion: '1 pieza (200g)' },
  { name: 'Hígado encebollado', category: 'carnes', caloriesPer100g: 180, defaultPortion: '1 porción (150g)' },
  { name: 'Pernil de cerdo', category: 'carnes', caloriesPer100g: 260, defaultPortion: '1 porción (150g)' },
  { name: 'Cazón', category: 'pescados', caloriesPer100g: 90, defaultPortion: '1 filete (150g)' },
  { name: 'Curvina', category: 'pescados', caloriesPer100g: 85, defaultPortion: '1 filete (150g)' },
  { name: 'Langostinos', category: 'pescados', caloriesPer100g: 85, defaultPortion: '1 porción (100g)' },
  { name: 'Camarones', category: 'pescados', caloriesPer100g: 99, defaultPortion: '1 porción (100g)' },
  { name: 'Pulpo cocido', category: 'pescados', caloriesPer100g: 82, defaultPortion: '1 porción (100g)' },
  { name: 'Ceviche de pescado', category: 'pescados', caloriesPer100g: 56, defaultPortion: '1 plato (200g)' },
  { name: 'Tofu firme', category: 'legumbres', caloriesPer100g: 76, defaultPortion: '1 porción (100g)' },
  { name: 'Tempeh', category: 'legumbres', caloriesPer100g: 193, defaultPortion: '1 porción (100g)' },
  { name: 'Edamame cocido', category: 'legumbres', caloriesPer100g: 121, defaultPortion: '1 taza (150g)' },
  { name: 'Hummus', category: 'legumbres', caloriesPer100g: 237, defaultPortion: '3 cucharadas (60g)' },
  { name: 'Falafel', category: 'legumbres', caloriesPer100g: 257, defaultPortion: '4 unidades (100g)' },
  { name: 'Pan pita', category: 'cereales', caloriesPer100g: 275, defaultPortion: '1 unidad (60g)' },
  { name: 'Pan de hamburguesa', category: 'cereales', caloriesPer100g: 275, defaultPortion: '1 unidad (60g)' },
  { name: 'Croissant', category: 'cereales', caloriesPer100g: 406, defaultPortion: '1 unidad (60g)' },
  { name: 'Bagel', category: 'cereales', caloriesPer100g: 250, defaultPortion: '1 unidad (100g)' },
  { name: 'Pizza de queso', category: 'comidas', caloriesPer100g: 266, defaultPortion: '1 porción (100g)' },
  { name: 'Pizza pepperoni', category: 'comidas', caloriesPer100g: 313, defaultPortion: '1 porción (100g)' },
  { name: 'Hamburguesa simple', category: 'comidas', caloriesPer100g: 250, defaultPortion: '1 unidad (200g)' },
  { name: 'Hot dog', category: 'comidas', caloriesPer100g: 247, defaultPortion: '1 unidad (150g)' },
  { name: 'Sandwich de jamón y queso', category: 'comidas', caloriesPer100g: 240, defaultPortion: '1 unidad (150g)' },
  { name: 'Tacos de pollo', category: 'comidas', caloriesPer100g: 185, defaultPortion: '2 unidades (150g)' },
  { name: 'Burrito de carne', category: 'comidas', caloriesPer100g: 210, defaultPortion: '1 unidad (300g)' },
  { name: 'Nachos con queso', category: 'comidas', caloriesPer100g: 306, defaultPortion: '1 porción (150g)' },
  { name: 'Sushi roll', category: 'comidas', caloriesPer100g: 143, defaultPortion: '6 piezas (150g)' },
  { name: 'Ensalada César', category: 'ensaladas', caloriesPer100g: 75, defaultPortion: '1 plato (300g)' },
  { name: 'Ensalada verde simple', category: 'ensaladas', caloriesPer100g: 30, defaultPortion: '1 plato (200g)' },
  { name: 'Ensalada de pasta', category: 'ensaladas', caloriesPer100g: 150, defaultPortion: '1 taza (200g)' },
  { name: 'Ensalada de frutas', category: 'ensaladas', caloriesPer100g: 85, defaultPortion: '1 taza (200g)' },
  { name: 'Palta/aguacate relleno', category: 'ensaladas', caloriesPer100g: 140, defaultPortion: '1/2 unidad (150g)' },
  { name: 'Arroz chino', category: 'comidas', caloriesPer100g: 160, defaultPortion: '1 taza (200g)' },
  { name: 'Pollo agridulce', category: 'comidas', caloriesPer100g: 180, defaultPortion: '1 porción (200g)' },
  { name: 'Carne mongoliana', category: 'comidas', caloriesPer100g: 220, defaultPortion: '1 porción (200g)' },
  { name: 'Lasagna', category: 'comidas', caloriesPer100g: 135, defaultPortion: '1 porción (250g)' },
  { name: 'Risotto', category: 'comidas', caloriesPer100g: 145, defaultPortion: '1 taza (200g)' },
  { name: 'Pollo al curry', category: 'comidas', caloriesPer100g: 140, defaultPortion: '1 porción (200g)' },
  { name: 'Estofado de res', category: 'comidas', caloriesPer100g: 110, defaultPortion: '1 plato (300g)' },
  { name: 'Guiso de lentejas', category: 'comidas', caloriesPer100g: 95, defaultPortion: '1 plato (300g)' },
  { name: 'Feijoada', category: 'comidas', caloriesPer100g: 125, defaultPortion: '1 plato (300g)' },
  { name: 'Moqueca de pescado', category: 'comidas', caloriesPer100g: 90, defaultPortion: '1 plato (300g)' },
  { name: 'Açaí bowl', category: 'comidas', caloriesPer100g: 70, defaultPortion: '1 bowl (300g)' },
  { name: 'Smoothie verde', category: 'bebidas', caloriesPer100ml: 40, defaultPortion: '1 vaso (300ml)' },
  { name: 'Smoothie de frutas', category: 'bebidas', caloriesPer100ml: 55, defaultPortion: '1 vaso (300ml)' },
  { name: 'Limonada', category: 'bebidas', caloriesPer100ml: 25, defaultPortion: '1 vaso (300ml)' },
  { name: 'Chicha de arroz', category: 'bebidas', caloriesPer100ml: 65, defaultPortion: '1 vaso (240ml)' },
  { name: 'Papelón con limón', category: 'bebidas', caloriesPer100ml: 30, defaultPortion: '1 vaso (300ml)' },
  { name: 'Té verde sin azúcar', category: 'bebidas', caloriesPer100ml: 1, defaultPortion: '1 taza (240ml)' },
  { name: 'Té dulce', category: 'bebidas', caloriesPer100ml: 20, defaultPortion: '1 taza (240ml)' },
  { name: 'Leche de almendras', category: 'bebidas', caloriesPer100ml: 17, defaultPortion: '1 vaso (240ml)' },
  { name: 'Leche de soya', category: 'bebidas', caloriesPer100ml: 33, defaultPortion: '1 vaso (240ml)' },
  { name: 'Suplemento de proteína en polvo', category: 'bebidas', caloriesPer100g: 400, defaultPortion: '1 scoop (30g)' },
  { name: 'Barra de proteína', category: 'dulces', caloriesPer100g: 350, defaultPortion: '1 barra (50g)' },
  { name: 'Granola', category: 'cereales', caloriesPer100g: 471, defaultPortion: '1/2 taza (50g)' },
  { name: 'Maíz tostado', category: 'cereales', caloriesPer100g: 370, defaultPortion: '1 taza (30g)' },
  { name: 'Platanitos/chifles', category: 'snacks', caloriesPer100g: 520, defaultPortion: '1 bolsa pequeña (40g)' },
  { name: 'Papas Lays', category: 'snacks', caloriesPer100g: 536, defaultPortion: '1 bolsa pequeña (40g)' },
  { name: 'Galletas saladas', category: 'snacks', caloriesPer100g: 450, defaultPortion: '6 unidades (30g)' },
  { name: 'Pretzels', category: 'snacks', caloriesPer100g: 380, defaultPortion: '1 porción (30g)' },
  { name: 'Popcorn sin mantequilla', category: 'snacks', caloriesPer100g: 387, defaultPortion: '1 taza (8g)' },
  { name: 'Yogur griego', category: 'lacteos', caloriesPer100g: 97, defaultPortion: '1 pote (200g)' },
  { name: 'Requesón/ricotta', category: 'lacteos', caloriesPer100g: 134, defaultPortion: '1/2 taza (100g)' },
  { name: 'Crema de leche', category: 'lacteos', caloriesPer100g: 345, defaultPortion: '2 cucharadas (30g)' },
  { name: 'Kéfir', category: 'lacteos', caloriesPer100ml: 41, defaultPortion: '1 vaso (200ml)' },
  { name: 'Pechuga de pavo', category: 'carnes', caloriesPer100g: 135, defaultPortion: '1 porción (100g)' },
  { name: 'Jamón de pavo', category: 'carnes', caloriesPer100g: 115, defaultPortion: '3 rebanadas (45g)' },
  { name: 'Tocino', category: 'carnes', caloriesPer100g: 541, defaultPortion: '2 tiras (16g)' },
  { name: 'Chorizo', category: 'carnes', caloriesPer100g: 330, defaultPortion: '1 unidad (70g)' },
  { name: 'Salchicha', category: 'carnes', caloriesPer100g: 290, defaultPortion: '1 unidad (50g)' },
  { name: 'Morcilla', category: 'carnes', caloriesPer100g: 280, defaultPortion: '1 unidad (80g)' },
  { name: 'Salsa de tomate', category: 'condimentos', caloriesPer100g: 42, defaultPortion: '2 cucharadas (30g)' },
  { name: 'Salsa BBQ', category: 'condimentos', caloriesPer100g: 130, defaultPortion: '2 cucharadas (30g)' },
  { name: 'Salsa de soya', category: 'condimentos', caloriesPer100g: 53, defaultPortion: '1 cucharada (15ml)' },
  { name: 'Vinagreta', category: 'condimentos', caloriesPer100g: 290, defaultPortion: '2 cucharadas (30g)' },
  { name: 'Mostaza', category: 'condimentos', caloriesPer100g: 66, defaultPortion: '1 cucharadita (5g)' },
  { name: 'Kétchup', category: 'condimentos', caloriesPer100g: 101, defaultPortion: '1 cucharada (15g)' },
  { name: 'Catsup', category: 'condimentos', caloriesPer100g: 101, defaultPortion: '1 cucharada (15g)' },
  { name: 'Aguacate/palta entero', category: 'frutas', caloriesPer100g: 160, defaultPortion: '1 unidad (200g)' },
  { name: 'Guayaba', category: 'frutas', caloriesPer100g: 68, defaultPortion: '1 unidad (100g)' },
  { name: 'Marañón', category: 'frutas', caloriesPer100g: 50, defaultPortion: '1 unidad (100g)' },
  { name: 'Pitahaya/dragon fruit', category: 'frutas', caloriesPer100g: 60, defaultPortion: '1 unidad (200g)' },
  { name: 'Guanábana', category: 'frutas', caloriesPer100g: 66, defaultPortion: '1 taza (200g)' },
  { name: 'Mamey', category: 'frutas', caloriesPer100g: 83, defaultPortion: '1 taza (200g)' },
  { name: 'Níspero', category: 'frutas', caloriesPer100g: 47, defaultPortion: '1 taza (150g)' },
  { name: 'Tamarindo', category: 'frutas', caloriesPer100g: 239, defaultPortion: '1 unidad (10g)' },
  { name: 'Cerezas', category: 'frutas', caloriesPer100g: 50, defaultPortion: '1 taza (150g)' },
  { name: 'Arándanos', category: 'frutas', caloriesPer100g: 57, defaultPortion: '1 taza (150g)' },
  { name: 'Kiwi', category: 'frutas', caloriesPer100g: 61, defaultPortion: '1 unidad (75g)' },
  { name: 'Ciruela', category: 'frutas', caloriesPer100g: 46, defaultPortion: '1 unidad (60g)' },
  { name: 'Higo', category: 'frutas', caloriesPer100g: 74, defaultPortion: '1 unidad (50g)' },
  { name: 'Dátil', category: 'frutas', caloriesPer100g: 282, defaultPortion: '3 unidades (24g)' },
  { name: 'Pasas', category: 'frutas', caloriesPer100g: 299, defaultPortion: '1 puñado (30g)' },
  { name: 'Ciruela pasa', category: 'frutas', caloriesPer100g: 240, defaultPortion: '3 unidades (30g)' },
];

module.exports = foods;
